name: Build
on:
  workflow_dispatch:
      inputs:
        gm_addr:
          description: "Address of the Global Metadata pointer:"
          required: true
        package_name:
          description: "Package name of target android app"
          default: "com.PigeonGames.Phigros"
          required: true

run-name: Deploy to ${{ inputs.package_name }} (${{ inputs.gm_addr }})

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - run: |
        chmod +x ./gradlew
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        sed -i "s/0x000000/${{ github.event.inputs.gm_addr }}/g" module/src/main/cpp/hack.h
        ./gradlew :module:assembleRelease
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package_name }}-${{ inputs.gm_addr }}
        path: out/magisk_module_release/
